name: phylofoundry
channels:
  - conda-forge
  - bioconda
  - defaults
  - smirarab
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-bio
  - scikit-learn>=1.3
  - umap-learn
  - hmmer
  - pyhmmer
  - mafft
  - pal2nal
  - clipkit
  - iqtree=3.*
  - treeshrink
  - r-base>=4.3
  - r-ggplot2
  - r-ape
  - r-aplot
  - r-dplyr
  - r-tidyr
  - r-scales
  - r-rcolorbrewer
  - r-optparse
  - r-ggnewscale
  - bioconductor-ggtree
  - bioconductor-treeio
  - bioconductor-ggtreeextra
  - biopython
  - matplotlib
  - scipy
  - diamond
  - mmseqs2
  - hyphy
  - treecluster
  - clinker-py
  - python-igraph
  - leidenalg
  - pip
  - pip:
    - logomaker
    - fair-esm
    - transformers
    - torch
    - streamlit
    - bqplot
    - pygenomeviz
    - pwlf
    - faiss-cpu
    - networkx
    - seaborn
    - .  # Install the current package in editable mode
